server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resume?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      #自动创建和更新表
      ddl-auto: update
    show-sql: true
    database: mysql
    #使用InnoDB引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  jackson:
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
      trigger-file: .reloadtrigger

debug: true
logging:
  file:
    max-history: 15
    max-size: 50M
  level:
    work.lovejava.life: DEBUG
    org.hibernate: ERROR
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: DEBUG
    java.sql.ResultSet: DEBUG
